### PR TITLE
Fix issue https://github.com/rancher/rke2/issues/4238

### PR DESCRIPTION
**Pull request by rajeeshkumarkk**
updated the docker image labels to fix the issue https://github.com/rancher/rke2/issues/4238

### CODE REVIEW

**Comment by rajeeshkumarkk** [comment]
Could you please review @matttrach @thomasferrandiz @manuelbuil  @rbrtbnfgl @mgfritch

**Comment by manuelbuil** [comment]
I'd like @matttrach to comment here since he is the author of the EPIC

**Comment by matttrach** [comment]
I think this addresses the spirit of the epic, but we should follow up to make sure that the images have the correct tags when they get to dockerhub.

**Review by matttrach — APPROVED** [review]

**Review by manuelbuil — APPROVED** [review]

**Comment by rajeeshkumarkk** [comment]
@manuelbuil thank you for approving the PR. Could you please merge?

**Pull request merged**
